# importing the dependencies

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score

# importing model

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier

# data collection and processing

In [ ]:
# loading the csv file to pandas dataframe
heart_data = pd.read_csv('/content/heart_disease_data.csv')

In [ ]:
heart_data.head()

   age  sex  cp  trestbps  chol  fbs  ...  exang  oldpeak  slope  ca  thal  target
0   63    1   3       145   233    1  ...      0      2.3      0   0     1       1
1   37    1   2       130   250    0  ...      0      3.5      0   0     2       1
2   41    0   1       130   204    0  ...      0      1.4      2   0     2       1
3   56    1   1       120   236    0  ...      0      0.8      2   0     2       1
4   57    0   0       120   354    0  ...      1      0.6      2   0     2       1

[5 rows x 14 columns]

In [ ]:
heart_data.shape

(303, 14)

In [ ]:
heart_data.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [ ]:
# check distribution of target variables
heart_data['target'].value_counts()

target
1    165
0    138
Name: count, dtype: int64

1-----> defective heart

0-----> healthy

split features and target

In [ ]:
x = heart_data.drop(columns = 'target' , axis =1)
y = heart_data['target']

In [ ]:
print(x)

     age  sex  cp  trestbps  chol  ...  exang  oldpeak  slope  ca  thal
0     63    1   3       145   233  ...      0      2.3      0   0     1
1     37    1   2       130   250  ...      0      3.5      0   0     2
2     41    0   1       130   204  ...      0      1.4      2   0     2
3     56    1   1       120   236  ...      0      0.8      2   0     2
4     57    0   0       120   354  ...      1      0.6      2   0     2
..   ...  ...  ..       ...   ...  ...    ...      ...    ...  ..   ...
298   57    0   0       140   241  ...      1      0.2      1   0     3
299   45    1   3       110   264  ...      0      1.2      1   0     3
300   68    1   0       144   193  ...      0      3.4      1   2     3
301   57    1   0       130   131  ...      1      1.2      1   1     3
302   57    0   1       130   236  ...      0      0.0      1   1     2

[303 rows x 13 columns]

In [ ]:
print(y)

0      1
1      1
2      1
3      1
4      1
      ..
298    0
299    0
300    0
301    0
302    0
Name: target, Length: 303, dtype: int64

# train test split

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2 ,stratify =y,random_state =3)

In [ ]:
print(x.shape,x_train.shape,x_test.shape)

(303, 13) (242, 13) (61, 13)

# comparing the performance of the models

In [ ]:
# list of models
models = [LogisticRegression(max_iter = 1000),SVC(kernel = 'linear'), KNeighborsClassifier(),RandomForestClassifier()]

In [ ]:
def compare_models_train_test():
 for model in models :
  model.fit(x_train,y_train)
  test_data_prediction = model.predict(x_test)
  accuracy = accuracy_score(y_test , test_data_prediction)
  print('accuracy score of the' , model ,'=' , accuracy)

In [ ]:
compare_models_train_test()

accuracy score of the LogisticRegression(max_iter=1000) = 0.7868852459016393
accuracy score of the SVC(kernel='linear') = 0.7704918032786885
accuracy score of the KNeighborsClassifier() = 0.6557377049180327
accuracy score of the RandomForestClassifier() = 0.7868852459016393

# cross validation

In [ ]:
cv_score_lr = cross_val_score(LogisticRegression(max_iter = 1000), X=x ,y=y , cv = 5)

print(cv_score_lr)
mean_accuracy_lr = sum(cv_score_lr)/len(cv_score_lr)

mean_accuracy_lr = round(mean_accuracy_lr*100)
mean_accuracy_lr = round(mean_accuracy_lr,2)
print(mean_accuracy_lr)

[0.80327869 0.86885246 0.85245902 0.86666667 0.75      ]
83

In [ ]:
cv_score_svc = cross_val_score(SVC(kernel = 'linear'), X=x ,y=y , cv = 5)
print('cross validation score of SVC =',cv_score_svc)
mean_accuracy_svc = sum(cv_score_svc)/len(cv_score_svc)

mean_accuracy_svc = round(mean_accuracy_svc*100)
mean_accuracy_svc = round(mean_accuracy_lr,2)
print(mean_accuracy_lr)

cross validation score of SVC = [0.81967213 0.8852459  0.80327869 0.86666667 0.76666667]
83

In [ ]:
cv_score_knn = cross_val_score(KNeighborsClassifier(), X=x ,y=y , cv = 5)
print('cross validation score of KNN =',cv_score_knn)

In [ ]:
cv_score_rf = cross_val_score(RandomForestClassifier(), X=x ,y=y , cv = 5)
print('cross validation score of Random Forest =',cv_score_rf)

# creating a function to compare the models

In [ ]:
# list of models
models = [LogisticRegression(max_iter = 1000),SVC(kernel = 'linear'), KNeighborsClassifier(),RandomForestClassifier()]

In [ ]:
def compare_models_cross_validation():
  for model in models :
    cv_score = cross_val_score(model,x,y,cv = 5)
    mean_accuracy = sum(cv_score)/len(cv_score)
    mean_accuracy_svc = mean_accuracy*1000
    mean_accuracy_svc = round(mean_accuracy,2)

    print(' cross validation for the ' ,model ,'=' ,cv_score)
    print('accuracy % of the ' , model , mean_accuracy )
    print('----------------')

In [ ]:
compare_models_cross_validation()

 cross validation for the  LogisticRegression(max_iter=1000) = [0.80327869 0.86885246 0.85245902 0.86666667 0.75      ]
accuracy % of the  LogisticRegression(max_iter=1000) 0.8282513661202187
----------------
 cross validation for the  SVC(kernel='linear') = [0.81967213 0.8852459  0.80327869 0.86666667 0.76666667]
accuracy % of the  SVC(kernel='linear') 0.8283060109289618
----------------
 cross validation for the  KNeighborsClassifier() = [0.60655738 0.6557377  0.57377049 0.73333333 0.65      ]
accuracy % of the  KNeighborsClassifier() 0.643879781420765
----------------
 cross validation for the  RandomForestClassifier() = [0.81967213 0.86885246 0.80327869 0.78333333 0.75      ]
accuracy % of the  RandomForestClassifier() 0.8050273224043716
----------------