# importing dependencies



```
# importing the dependencies
```

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV

# importing model

In [ ]:
# importing model
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier

In [ ]:
heart_data = pd.read_csv('/content/heart_disease_data.csv')

In [ ]:
heart_data.head()

   age  sex  cp  trestbps  chol  fbs  ...  exang  oldpeak  slope  ca  thal  target
0   63    1   3       145   233    1  ...      0      2.3      0   0     1       1
1   37    1   2       130   250    0  ...      0      3.5      0   0     2       1
2   41    0   1       130   204    0  ...      0      1.4      2   0     2       1
3   56    1   1       120   236    0  ...      0      0.8      2   0     2       1
4   57    0   0       120   354    0  ...      1      0.6      2   0     2       1

[5 rows x 14 columns]

In [ ]:
heart_data.shape

(303, 14)

In [ ]:
heart_data.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [ ]:
# check the distribution of target variable
heart_data['target'].value_counts()

target
1    165
0    138
Name: count, dtype: int64

1-----> defective heart

0-----> healthy heart

# splitting the features and target

In [ ]:
x = heart_data.drop(columns ='target' , axis = 1)
y = heart_data['target']

In [ ]:
print(x)

     age  sex  cp  trestbps  chol  ...  exang  oldpeak  slope  ca  thal
0     63    1   3       145   233  ...      0      2.3      0   0     1
1     37    1   2       130   250  ...      0      3.5      0   0     2
2     41    0   1       130   204  ...      0      1.4      2   0     2
3     56    1   1       120   236  ...      0      0.8      2   0     2
4     57    0   0       120   354  ...      1      0.6      2   0     2
..   ...  ...  ..       ...   ...  ...    ...      ...    ...  ..   ...
298   57    0   0       140   241  ...      1      0.2      1   0     3
299   45    1   3       110   264  ...      0      1.2      1   0     3
300   68    1   0       144   193  ...      0      3.4      1   2     3
301   57    1   0       130   131  ...      1      1.2      1   1     3
302   57    0   1       130   236  ...      0      0.0      1   1     2

[303 rows x 13 columns]

In [ ]:
print(y)

0      1
1      1
2      1
3      1
4      1
      ..
298    0
299    0
300    0
301    0
302    0
Name: target, Length: 303, dtype: int64

In [ ]:
x = np.asarray(x)
y = np.asarray(y)

# model selection

1. comparing the model with default hyperparameter values using cross validation

In [ ]:
# list of models
models = [LogisticRegression(), KNeighborsClassifier(), RandomForestClassifier()]

In [ ]:
def compare_models_cross_validation():
  for model in models:

    cv_score = cross_val_score(model,x,y,cv=5)
    mean_accuracy = sum(cv_score)/len(cv_score)
    mean_accuracy = mean_accuracy*100
    mean_accuracy = round(mean_accuracy,2)

    print('cross validation accuracies for the ', model , '=' ,cv_score)
    print('Accuracy score of the ' , model, '=' ,mean_accuracy, '%')
    print('-------------------------\n')

In [ ]:
compare_models_cross_validation()

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

cross validation accuracies for the  LogisticRegression() = [0.81967213 0.86885246 0.85245902 0.85       0.75      ]
Accuracy score of the  LogisticRegression() = 82.82 %
-------------------------

cross validation accuracies for the  KNeighborsClassifier() = [0.60655738 0.6557377  0.57377049 0.73333333 0.65      ]
Accuracy score of the  KNeighborsClassifier() = 64.39 %
-------------------------

cross validation accuracies for the  RandomForestClassifier() = [0.81967213 0.8852459  0.80327869 0.81666667 0.78333333]
Accuracy score of the  RandomForestClassifier() = 82.16 %
-------------------------

# comparing the models with different hyperparameter value using gridsearchcv

In [ ]:
# list of models
models = [LogisticRegression(max_iter = 10000),svc() ,KNeighborsClassifier(), RandomForestClassifier()]

NameError: name 'svc' is not defined

In [ ]:
from sklearn.svm import SVC

In [ ]:
# list of models
models = [LogisticRegression(max_iter = 10000), SVC(), KNeighborsClassifier(), RandomForestClassifier()]

In [ ]:
# create dictionary that contains hyperparameter value for above models

model_hyperparameters = {

                         'log_reg_hyperparameters' : {
                             'C' : [1,5,10,20]
                         },
                         'SVC_hyperparameters' : {
                             'kernel' : ['linear' , 'poly', 'rbf', 'sigmoid'],
                             'C' : [1,5,10,20]
                         },
                         'KNN_hyperparameters' : {
                             'n_neighbors' : [3,5,10]
                         },
                         'random_forest_hyperparameters' : {
                             'n_estimators' : [10,20,50,100]
                         }
}

In [ ]:
print(model_hyperparameters.keys())

dict_keys(['log_reg_hyperparameters', 'SVC_hyperparameters', 'KNN_hyperparameters', 'random_forest_hyperparameters'])

In [ ]:
model_keys = list(model_hyperparameters.keys())
print(model_keys)

['log_reg_hyperparameters', 'SVC_hyperparameters', 'KNN_hyperparameters', 'random_forest_hyperparameters']

In [ ]:
model_hyperparameters['SVC_hyperparameters']

{'kernel': ['linear', 'poly', 'rbf', 'sigmoid'], 'C': [1, 5, 10, 20]}

In [ ]:
model_keys[2]

'KNN_hyperparameters'

In [ ]:
model_hyperparameters[model_keys[1
                                 ]]

{'kernel': ['linear', 'poly', 'rbf', 'sigmoid'], 'C': [1, 5, 10, 20]}

# apply gridsearchcv

In [ ]:
def ModelSelection(models , hyperparameters_dictionary):
  result = []
  i = 0
  for model in models:

    keys = model_keys[i]
    params = hyperparameters_dictionary[keys]
    i +=1
    print(model)
    print(params)
    classifier = GridSearchCV(model, params,cv =5)
    # fitting the data to classifier
    classifier.fit(x,y)
    result.append({
        'model used' : model,
        'highest score' : classifier.best_score_,
        'best hyperparameters' : classifier.best_params_
    })
    result_dataframe = pd.DataFrame(result,columns = ['model used','highest score','best hyperparameters'])
    return result_dataframe

In [ ]:
ModelSelection(models, model_hyperparameters)

LogisticRegression(max_iter=10000)
{'C': [1, 5, 10, 20]}

                           model used  highest score best hyperparameters
0  LogisticRegression(max_iter=10000)       0.831585             {'C': 5}